theme: jekyll-theme-minimal
# title: Kaufman Lab
description: Resources for Kaufman Lab Staff, Students, and Collaborators
# logo: assets/images/DEOHS-Logo-Centered-Purple-Web-Transparency.png
show_downloads: false